import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { auth } from "@/auth";
import { SettingsProvider } from "@/lib/utilComponents/SettingsContext";
import { defaultSettings, getSettingsData } from "@/lib/data";
import NavbarBottom from "@/components/navbarBottom/NavbarBottom";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700', '900'],
  style: ['italic', 'normal'],
  variable: '--font-roboto', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();
  let settings = defaultSettings;

  if (session) {
    settings = await getSettingsData(session.user?.id) || defaultSettings;
  }

  console.log(session?.user?.image)

  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body
        className={`font-roboto antialiased`}
      >
        <SettingsProvider settings={settings} userId={session?.user?.id}>
            <Navbar
              imgUrl={session?.user?.image}
              username={session?.user?.name || ""}
            />
            {children}
            <NavbarBottom />
        </SettingsProvider>
      </body>
    </html>
  );
}
