import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { auth } from "@/auth";
import { SettingsProvider } from "@/lib/utilComponents/useSettings";
import { defaultSettings, getSettingsData } from "@/lib/data";
import NavbarBottom from "@/components/navbarBottom/NavbarBottom";
import ThemeProvider from "@/lib/utilComponents/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();
  let settings = defaultSettings;

  if (session) {
    settings = await getSettingsData(session.user?.id) || defaultSettings;
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SettingsProvider settings={settings}>
          <ThemeProvider>
            <Navbar imgUrl={"https://pbs.twimg.com/profile_images/874661809139073025/X8yzIhNy_400x400.jpg"}/>
            {children}
            <NavbarBottom />
          </ThemeProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}
